# Set the maximum line length to 187:
line-length = 190
indent-width = 4  # default anyways
target-version = "py312"

[format]
quote-style = "double"
indent-style = "space"  # indent with spaces, rather than tabs.

# [lint]
# Add the `line-too-long` rule to the enforced rule set:
# extend-select = ["E501"]
